FROM node:14 as build-stage
WORKDIR /skripsi
COPY /client .
RUN yarn cache clean
RUN yarn install
RUN yarn build

FROM nginx as production-stage
RUN mkdir -p /app/skripsi
COPY --from=build-stage /easydev/build /app/skripsi
COPY /template/nginx.conf /etc/nginx/nginx.conf