/**
 * @author - Mochamad Yudi Sobari
 * @define - SEARCH
 * @desc - Params & filter search
 * @type {string}
 */

export const IS_SEARCH                          = "IS_SEARCH"
export const IS_SEARCH_KEY                      = "IS_SEARCH_KEY"

/**
 * @author - Mochamad Yudi Sobari
 * @desc - FILTER BOOKING
 * @type {string}
 */

/**
 * BOOKING SEARCH - HARGA
 */

export const SEARCH_FILTER_BK_MIN_HARGA    = "SEARCH_FILTER_BK_MIN_HARGA"
export const SEARCH_FILTER_BK_MAX_HARGA    = "SEARCH_FILTER_BK_MAX_HARGA"
/**
 * BOOKING SEARCH - DATE
 */
export const SEARCH_FILTER_BK_START_DATE   = "SEARCH_FILTER_BK_START_DATE"
export const SEARCH_FILTER_BK_START_MONTH  = "SEARCH_FILTER_BK_START_MONTH"
export const SEARCH_FILTER_BK_END_DATE     = "SEARCH_FILTER_BK_END_DATE"
export const SEARCH_FILTER_BK_END_MONTH    = "SEARCH_FILTER_BK_END_MONTH"
/**
 * BOOKING EARCH - LOCATION
 */
export const SEARCH_FILTER_BK_OPT_LOC      = "SEARCH_FILTER_BK_OPT_LOC"
export const SEARCH_FILTER_BK_OPT_LOC_NAME = "SEARCH_FILTER_BK_OPT_LOC_NAME"
export const SEARCH_FILTER_BK_OPT_LATLONG  = "SEARCH_FILTER_BK_OPT_LATLONG"

/**
 * BOOKING SEARCH - FASILITAS
 */
export const SEARCH_FILTER_BK_FAC_TOILET   = "SEARCH_FILTER_BK_FAC_TOILET"
export const SEARCH_FILTER_BK_FAC_BTYPE    = "SEARCH_FILTER_BK_FAC_BTYPE"
export const SEARCH_FILTER_BK_FAC_RTYPE    = "SEARCH_FILTER_BK_FAC_RTYPE"
export const SEARCH_FILTER_BK_FAC_WIFI     = "SEARCH_FILTER_BK_FAC_WIFI"
export const SEARCH_FILTER_BK_FAC_CANTEEN  = "SEARCH_FILTER_BK_FAC_CANTEEN"

/**
 * @author - Mochamad Yudi Sobari
 * @desc - FILTER TICKET
 * @type {string}
 */

/**
 * TICKET SEARCH - HARGA
 */
export const SEARCH_FILTER_TC_MIN_HARGA     = "SEARCH_FILTER_TC_MIN_HARGA"
export const SEARCH_FILTER_TC_MAX_HARGA     = "SEARCH_FILTER_TC_MAX_HARGA"

/**
 * TICKET SEARCH - LOCATION
 */
export const SEARCH_FILTER_TC_OPT_LOC       = 'SEARCH_FILTER_TC_OPT_LOC'
export const SEARCH_FILTER_TC_OPT_LOC_NAME  = "SEARCH_FILTER_TC_OPT_LOC_NAME"
export const SEARCH_FILTER_TC_OPT_LATLONG   = "SEARCH_FILTER_TC_OPT_LATLONG"

/**
 * TICKET SEARCH - FASILITAS
 */
export const SEARCH_FILTER_TC_FAC_TOILET    = "SEARCH_FILTER_TC_FAC_TOILET"
export const SEARCH_FILTER_TC_FAC_WIFI      = "SEARCH_FILTER_TC_FAC_WIFI"
export const SEARCH_FILTER_TC_FAC_CANTEEN   = "SEARCH_FILTER_TC_FAC_CANTEEN"
export const SEARCH_FILTER_TC_FAC_LOUNGE    = "SEARCH_FILTER_TC_FAC_LOUNGE"

/**
 * TICKET SEARCH - TYPE
 */
export const SEARCH_FILTER_TC_OPT           = "SEARCH_FILTER_TC_OPT"